name: widget
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '^3.11.5'
  flutter: '>=3.41.9'

dependencies:
  app_config:
    path: ../app_config

  cc_sdk:
    path: ../../libraries/cc_sdk
  cc_sdk_ui:
    path: ../../libraries/cc_sdk_ui

  flutter:
    sdk: flutter
  lottie: ^3.3.3
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1

  shared_preferences: ^2.5.5
  theme:
    path: ../theme

  url_launcher: ^6.3.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
