name: cc_sdk
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  android_id:
  ansicolor:

  connectivity_plus:
  crypto:
  custom_refresh_indicator:

  deep_collection:
  device_info_plus: 11.5.0
  dio:

  equatable:
  flutter:
    sdk: flutter

  flutter_animation_progress_bar:
  flutter_bounceable:
  flutter_spinkit:
  flutter_svg:

  get:
  google_fonts:

  intl:

  keyboard_dismisser:

  mask_text_input_formatter:
  multiple_result:

  package_info_plus: 8.3.1

  quiver:

  shimmer:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter