source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-firebase_app_distribution"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
if File.exist?(plugins_path)
  eval(File.read(plugins_path), binding)
end
