default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    flavor = options[:flavor] || "uat"

    # 1. Setup API Key (to bypass 2FA)
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: true
    )

    # 2. Prepare Flutter artifacts
    # Prepares the ios/ folder and compiled Dart code
    sh("cd ../.. && flutter build ios --release --flavor #{flavor} --no-codesign")

    # 3. Build App (Gym)
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      include_bitcode: false,
      export_method: "app-store",
      api_key: api_key,
      output_directory: "../build/ios/ipa",
      output_name: "Runner.ipa"
    )

    # 4. Upload to TestFlight (Pilot)
    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/Runner.ipa",
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
